IF NOT EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE [name] = 'MouseRecorder')
BEGIN
	PRINT 'Creating "MouseRecorder" database"..'

	CREATE DATABASE [MouseRecorder]
	 CONTAINMENT = NONE
	 ON  PRIMARY 
	( NAME = N'MouseRecorder', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQL\MSSQL\DATA\MouseRecorder.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
	 LOG ON 
	( NAME = N'MouseRecorder_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQL\MSSQL\DATA\MouseRecorder_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [MouseRecorder].[dbo].[sp_fulltext_database] @action = 'enable'
	end

	ALTER DATABASE [MouseRecorder] SET ANSI_NULL_DEFAULT OFF 
	ALTER DATABASE [MouseRecorder] SET ANSI_NULLS OFF 
	ALTER DATABASE [MouseRecorder] SET ANSI_PADDING OFF 
	ALTER DATABASE [MouseRecorder] SET ANSI_WARNINGS OFF 
	ALTER DATABASE [MouseRecorder] SET ARITHABORT OFF 
	ALTER DATABASE [MouseRecorder] SET AUTO_CLOSE OFF 
	ALTER DATABASE [MouseRecorder] SET AUTO_SHRINK OFF 
	ALTER DATABASE [MouseRecorder] SET AUTO_UPDATE_STATISTICS ON 
	ALTER DATABASE [MouseRecorder] SET CURSOR_CLOSE_ON_COMMIT OFF 
	ALTER DATABASE [MouseRecorder] SET CURSOR_DEFAULT  GLOBAL 
	ALTER DATABASE [MouseRecorder] SET CONCAT_NULL_YIELDS_NULL OFF 
	ALTER DATABASE [MouseRecorder] SET NUMERIC_ROUNDABORT OFF 
	ALTER DATABASE [MouseRecorder] SET QUOTED_IDENTIFIER OFF 
	ALTER DATABASE [MouseRecorder] SET RECURSIVE_TRIGGERS OFF 
	ALTER DATABASE [MouseRecorder] SET  DISABLE_BROKER 
	ALTER DATABASE [MouseRecorder] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	ALTER DATABASE [MouseRecorder] SET DATE_CORRELATION_OPTIMIZATION OFF 
	ALTER DATABASE [MouseRecorder] SET TRUSTWORTHY OFF 
	ALTER DATABASE [MouseRecorder] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	ALTER DATABASE [MouseRecorder] SET PARAMETERIZATION SIMPLE 
	ALTER DATABASE [MouseRecorder] SET READ_COMMITTED_SNAPSHOT OFF 
	ALTER DATABASE [MouseRecorder] SET HONOR_BROKER_PRIORITY OFF 
	ALTER DATABASE [MouseRecorder] SET RECOVERY FULL 
	ALTER DATABASE [MouseRecorder] SET  MULTI_USER 
	ALTER DATABASE [MouseRecorder] SET PAGE_VERIFY CHECKSUM  
	ALTER DATABASE [MouseRecorder] SET DB_CHAINING OFF 
	ALTER DATABASE [MouseRecorder] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	ALTER DATABASE [MouseRecorder] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	ALTER DATABASE [MouseRecorder] SET DELAYED_DURABILITY = DISABLED 
	ALTER DATABASE [MouseRecorder] SET QUERY_STORE = OFF
	ALTER DATABASE [MouseRecorder] SET  READ_WRITE 
END
ELSE
	PRINT 'The database "MouseRecorder" already exists..'